AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - com.siteminder.tlc::email-backend
Resources:
  EmailBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.siteminder.tlc.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/email-backend-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  EmailBackendApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/email/send'
    Export:
      Name: EmailBackendApi
